### ISSUE TITLE
Wrong color bar labels

### ISSUE THREAD

**Issue by aflaxman** [jakevdp/mpld3#247]
From StackOverflow http://stackoverflow.com/questions/26019619/wrong-colorbar-labels-using-mpld3

> I am using mpld3 to draw some plots in a browser. The scatter-plot is showing the correct colors, but the colorbar for the plot has the wrong labels. The colorbar is always labeled from 0 to 1, although vmin and vmax are different. Any ideas?

Minimal example code:
```
import numpy as np, matplotlib.pyplot as plt, mpld3
%matplotlib inline

np.random.seed(12345)
xList = np.random.normal(size=25)
yList = np.random.normal(size=25)
zList = np.random.normal(size=25)

im=plt.scatter(xList,yList,edgecolors='none',c=zList)
cbar=plt.colorbar(im)

mpld3.display()
```

Should look like:

![image](https://cloud.githubusercontent.com/assets/51236/4435139/b3edee3e-4736-11e4-8c5c-274000dc9f04.png)

Currently looks like:

![image](https://cloud.githubusercontent.com/assets/51236/4435140/c932143c-4736-11e4-99bc-f783378530d8.png)

**Comment by aflaxman** [comment]
When I was working on formatting, I fixed this, and didn't even realize it. Cool:

![image](https://cloud.githubusercontent.com/assets/51236/7876991/11faebd8-0589-11e5-9a7f-0f84c8536c24.png)

It should work if you install the latest version from GitHub, but please re-open if not.

**Comment by jsignell** [comment]
I grabbed the most recent version from GitHub and it worked great with `mpld3.show()` and `mpld3.enable_notebook()` but not with `mpld3.display()`. Any ideas why that would be?
![image](https://cloud.githubusercontent.com/assets/4806877/11376160/0c815d8c-92d7-11e5-952a-9e557f38d14f.png)

**Comment by jakevdp** [comment]
``display`` will by default use the javascript libraries from the web. Try ``display(local=True)`` to use the local version of the javascript.

**Comment by jsignell** [comment]
I must have not installed it properly. When I put `display(local=True)` my notebook threw an error when it tried to download `d3_src`, `mpld3_src` using `install_nbextension`  "path must be a string pointing to a single extension to install; call this function multiple times to install multiple extensions"

**Comment by jakevdp** [comment]
hmm... this might be something that has changed in the IPython notebook since I wrote the function. They have had a pretty ambitious development cycle over the last couple years, and I've found it breaks hacks like these fairly often.
