### ISSUE TITLE
Strange "None" label around the zoom/home buttons

### ISSUE THREAD

**Issue by chanansh** [jakevdp/mpld3#280]
When I output a figure to an html I get around the tool button.
Below is a screenshot of the problem and the chrome inspection of the element
![image](https://cloud.githubusercontent.com/assets/5981644/6225122/a76df1c8-b68e-11e4-8687-907f900f2853.png).

Where does this "None" comes from?

![image](https://cloud.githubusercontent.com/assets/5981644/6225102/6047670c-b68e-11e4-851a-2c3ca8882030.png)

![image](https://cloud.githubusercontent.com/assets/5981644/6225114/74bdc726-b68e-11e4-91c0-c54dd718d1d0.png)

**Comment by jakevdp** [comment]
That is the legend title, which ends up there because of issues with coordinate transforms. See #275.  I'm going to close this as a duplicate.
