### ISSUE TITLE
set_xticklabels has no effect after mpld3.enable_notebook()

### ISSUE THREAD

**Issue by ketch** [jakevdp/mpld3#288]
In the Jupyter notebook, after running

    mpld3.enable_notebook()

it seems that any call to the matplotlib method

    axis.set_xticklabels()

has no effect.  For instance, running the example here:

http://matplotlib.org/1.2.1/examples/pylab_examples/integral_demo.html

gives a plot with numeric tick labels (rather than 'a', 'b').

**Comment by philippjfr** [comment]
Have a look at the README on the main page, I'll quote it here:

>The following is a non-exhausive list of features that are yet to be supported:

> * tick specification & formatting

This is probably one of the most important missing features and a lot of us would love to see it implemented but so far no one has volunteered to have a go at it.

**Comment by ketch** [comment]
Whoops, sorry for missing that, and thanks for the explanation.  Feel free to close this -- or perhaps it should be left open.

**Comment by philippjfr** [comment]
Happy to help (or not help to be precise). I'm not actually on the development team, just happen to subscribe to the issues.

**Comment by aflaxman** [comment]
Actually, I have made some progress on this.  I think if you use the latest version of `mpld3` you will get the text ticks:

![image](https://cloud.githubusercontent.com/assets/51236/7619122/8216c178-f96b-11e4-9ccc-817790b9fd37.png)

It still does not show the x and y axis labels, or the integral, but the labels were the most critical part for me.  Patches welcome!

**Comment by philippjfr** [comment]
Oh that's great news, what's the status on hiding axes and tick labels? How much work do you think that would be?

**Comment by ketch** [comment]
Nice, it works for me after upgrading to the current master.

**Comment by aflaxman** [comment]
You can make the ticks or tick labels go away now, and making the axes go away would be a good intro project for `mpld3` development:

![image](https://cloud.githubusercontent.com/assets/51236/7619578/8970cfa6-f96e-11e4-8074-389e16280349.png)
