### ISSUE TITLE
Colorbar for imshow() is incorrect

### ISSUE THREAD

**Issue by HackerMD** [jakevdp/mpld3#295]
When adding a colorbar to an image

```{python}
import pylab as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(2, 2, 1)
ax.imshow(images[i], cmap='gray')

divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="10%", pad=0.05)
fig.colorbar(im, cax=cax)
```

the values are always in the range(0, 1) independing of 'vmin' and 'vmax' of the image.

**Comment by aflaxman** [comment]
I believe that this is fixed in the latest version of the code on GitHub (see #247).  Can you see if that works for you?

**Comment by HackerMD** [comment]
Works fine with the GitHub code! I used the code installed via ```pip install mpld3```.

Great! Thanks for immediate reply!
Would be nice if you could update the code at some point!

And by the way: awesome package!

**Comment by HackerMD** [comment]
Just noticed something else. The colors in the colorbar don't correspond to the values in the legend.

**Comment by aflaxman** [comment]
That's not good!  I think it's your fault, though.  When I change your code so that `im` is assigned in the code block, it works for me: http://nbviewer.ipython.org/gist/aflaxman/c4b41952b286d43b2775

**Comment by HackerMD** [comment]
Sorry, that was a copy-past error.

Shouldn't the colors in the colorbar be displayed in a continuous way, i.e. dark at the bottom and lighter towards to top? In your example the color between -1.6 and -2.4 is darker than the one between -2.4 and -3.2.

 ```plt.show()``` shows it as excepted. Is this a problem with discretisation?

**Comment by jakevdp** [comment]
I believe that's a problem with d3 not correctly displaying a quadmesh when the color is partially transparent. I'm not sure that HTML SVG is capable of doing that, so mpld3 currently uses the best approximation I could come up with.

**Comment by jakevdp** [comment]
note that it works a bit better with colors rather than grayscale.

**Comment by HackerMD** [comment]
Thank you very much for looking into it! I will have to live with it then..

**Comment by aflaxman** [comment]
Oh, that is so weird.  We make the colors in the colorbar by stacking up a ton of 1px tall paths.  There is some issue with repeated colors due to rounding, but I can't figure out why that leads to the non-continuous appearance of the gradient.  Here is a screenshot, though:

![image](https://cloud.githubusercontent.com/assets/51236/7947051/6fb3ec12-092f-11e5-8862-0cdc43a02333.png)

That is from Chrome.  It looks bad in a different way on Firefox and IE.
