### ISSUE TITLE
Support for xkcd mode

### ISSUE THREAD

**Issue by pelegm** [jakevdp/mpld3#313]
At least with Python 2, it seems like mpld3 does not support `xkcd` mode. The plot simply becomes "normal" back again. It would be nice if that feature was supported. If that's too complicated, perhaps a warning should be issued on runtime.

**Comment by pelegm** [comment]
Relevant SO questioin: http://stackoverflow.com/questions/27082646/how-do-you-import-an-xkcd-fig-to-html-using-mpld3.

**Comment by jakevdp** [comment]
Hi, This probably isn't going to happen, unless someone specifically decides to tackle it. I'm not sure how I'd even begin at that. Note that even some of the matplotlib backends don't support XKCD mode.

**Comment by pelegm** [comment]
Thanks for your reply. I'll close it then.

**Comment by ubershmekel** [comment]
I personally would have considered using mpld3 instead of plotlyjs if xkcd mode was supported. I much prefer my graphs show their potential inaccuracy through squiggly lines. Perhaps instead of closing this issue label it as a "feature request"?
