### ISSUE TITLE
xtickslabel does not work in display, but in figure export

### ISSUE THREAD

**Issue by MaximilianHoffmann** [jakevdp/mpld3#327]
I am not sure whether this is a bug or a principal limitation or nothing of both...

    f=plt.figure(figsize=[10,10])
    ax=plt.subplot(1,1,1)
    ax.set_xlabel('Time')
    ax.set_ylabel('Neurons')
    tr_im=plt.imshow(trace1.df_f[labels,:],extent=[0,trace1.n_t,0,len(labels)],aspect='auto')
    tr_im.set_interpolation('nearest')
    plt.gca().set_xticks(range(0,len(trace1.timestamps),500))
    plt.gca().set_xticklabels(trace1.timestamps[::500])
    plt.colorbar()
    tr_im.set_cmap('coolwarm')
    tr_im.set_clim([0,0.2])

if I export the figure with plt.savefig, the xticks commands work and give the right results, in the notebook things are unchanged.

Many Thanks for this great package!

**Comment by jakevdp** [comment]
This is a known bug. mpld3 does not support fixed tick labels. See https://github.com/jakevdp/mpld3/issues/278

**Comment by MaximilianHoffmann** [comment]
Ok, then I am sorry.Closed
